# Generated by Django 4.2.6 on 2023-10-24 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("verified_status", models.BooleanField(default=False)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                ("bio", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("birthdate", models.DateField()),
                ("staff_status", models.BooleanField(default=False)),
                ("active_status", models.BooleanField(default=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gender_name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("interest_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="InterestCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("marital_status_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="UserRatingEnum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("parent_age", models.IntegerField()),
                ("child_age", models.IntegerField()),
                (
                    "child_gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.gender"
                    ),
                ),
                (
                    "child_interest",
                    models.ManyToManyField(
                        related_name="child_interest", to="user.interest"
                    ),
                ),
                (
                    "marital_id",
                    models.ManyToManyField(
                        related_name="parent_marital_preference",
                        to="user.maritalstatus",
                    ),
                ),
                (
                    "parent_gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_gender",
                        to="user.gender",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photos",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interest",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.interestcategory"
            ),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userratingenum",
                    ),
                ),
                (
                    "user_id_given",
                    models.ManyToManyField(
                        related_name="grades_given", to="user.customuser"
                    ),
                ),
                (
                    "user_id_received",
                    models.ManyToManyField(
                        related_name="grades_received", to="user.customuser"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.gender"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_users",
                related_query_name="custom_user_groups",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="marital_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.maritalstatus"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferences_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.userpreferences"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="customuser_set",
                related_query_name="customuser",
                to="auth.permission",
            ),
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("birthdate", models.DateField()),
                ("bio", models.TextField()),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "gender_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_gender",
                        to="user.gender",
                    ),
                ),
                (
                    "interest_id",
                    models.ManyToManyField(
                        related_name="child_interests", to="user.interest"
                    ),
                ),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
            ],
        ),
    ]
