# Generated by Django 4.2.6 on 2023-10-20 09:48

import apps.user.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            (apps.user.models.GenderEnum["MALE"], "M"),
                            (apps.user.models.GenderEnum["FEMALE"], "F"),
                            (apps.user.models.GenderEnum["OTHER"], "O"),
                        ],
                        max_length=2,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("verified_status", models.BooleanField(default=False)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                ("bio", models.TextField()),
                ("location", models.TextField()),
                ("birthdate", models.DateField()),
                ("preferences", models.CharField(blank=True, max_length=500)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("staff_status", models.BooleanField(default=False)),
                ("active_status", models.BooleanField(default=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("groups", models.TextField()),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPhoto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "photos",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grade", models.CharField(choices=[], max_length=255)),
                (
                    "user_id_given",
                    models.ManyToManyField(
                        related_name="grades_given", to="user.customuser"
                    ),
                ),
                (
                    "user_id_received",
                    models.ManyToManyField(
                        related_name="grades_received", to="user.customuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenderInterest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gender_id",
                    models.CharField(
                        choices=[
                            (apps.user.models.GenderEnum["MALE"], "M"),
                            (apps.user.models.GenderEnum["FEMALE"], "F"),
                            (apps.user.models.GenderEnum["OTHER"], "O"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user_account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Children",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("age", models.PositiveIntegerField()),
                ("bio", models.TextField()),
                ("interests", models.CharField(blank=True, max_length=500)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customuser",
                    ),
                ),
            ],
        ),
    ]
