# Generated by Django 4.2.6 on 2023-10-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="genderinterest",
            name="user_account_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.customuser"
            ),
        ),
    ]
