# Generated by Django 4.2.6 on 2023-11-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="first_name",
            field=models.CharField(default="Kiddo", max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ChildPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="child_pictures/")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="user.child",
                    ),
                ),
            ],
        ),
    ]
