# Generated by Django 4.2.6 on 2023-11-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_child_first_name_childpicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="first_name",
            field=models.CharField(default="Kiddo", max_length=30),
        ),
    ]
