<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-11-09 10:37
=======
# Generated by Django 4.2.6 on 2023-11-10 12:17
>>>>>>> cf20bf65532dc9e278c9e4c997171cac85dde6cb

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_child_first_name_childpicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="first_name",
            field=models.CharField(default="Kiddo", max_length=30),
        ),
    ]
