# Generated by Django 4.2.6 on 2023-11-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_child_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="gender_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_gender",
                to="user.gender",
            ),
        ),
    ]
