# Generated by Django 4.2.6 on 2023-11-17 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_child_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blocked_users",
            field=models.ManyToManyField(
                related_name="blocked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="disliked_users",
            field=models.ManyToManyField(
                related_name="disliked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="liked_users",
            field=models.ManyToManyField(
                related_name="liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
