# Generated by Django 4.2.6 on 2023-11-17 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_customuser_blocked_users_customuser_disliked_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="blocked_users",
            field=models.ManyToManyField(
                blank=True, related_name="blocked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="disliked_users",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
