# Generated by Django 4.2.6 on 2023-11-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_child_gender_id"),
        ("user", "0006_alter_customuser_blocked_users_and_more"),
    ]

    operations = []
