# Generated by Django 4.2.6 on 2023-12-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_customuser_blocked_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("social", models.CharField(unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.socialcategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="socials",
            field=models.ManyToManyField(related_name="socials", to="user.social"),
        ),
    ]
