# Generated by Django 4.2.6 on 2023-12-01 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_socialcategory_social_customuser_socials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="socials",
        ),
        migrations.AddField(
            model_name="customuser",
            name="github",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="instagram",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="twitter",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="website",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.DeleteModel(
            name="Social",
        ),
        migrations.DeleteModel(
            name="SocialCategory",
        ),
    ]
