# Generated by Django 4.2.6 on 2023-11-10 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_room_remove_message_chat_alter_message_recipient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="id",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="id",
            new_name="uuid",
        ),
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
        migrations.RemoveField(
            model_name="room",
            name="slug",
        ),
    ]
